# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 09:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMERO_CNV', models.IntegerField()),
                ('TIPO_DOC_MADRE', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')])),
                ('NUMERO_DOC_MADRE', models.CharField(blank=True, max_length=35, null=True, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[a-zA-Z0-9]{1,35}$')])),
                ('PRIMER_APELLIDO_MADRE', models.CharField(blank=True, max_length=40, null=True)),
                ('SEGUNDO_APELLIDO_MADRE', models.CharField(blank=True, max_length=40, null=True)),
                ('PRENOMBRES_MADRE', models.CharField(blank=True, max_length=50, null=True)),
                ('SEXO_NACIDO', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')])),
                ('FECHA_NACIDO', models.CharField(blank=True, max_length=8, null=True)),
                ('HORA_NACIDO', models.CharField(blank=True, max_length=6, null=True)),
                ('PESO_NACIDO', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(8000)])),
                ('TALLA_NACIDO', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(99)])),
                ('APGAR_UNO_NACIDO', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('APGAR_CINCO_NACIDO', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('ETNIA_NACIDO', models.CharField(blank=True, max_length=6, null=True)),
                ('NU_NACIDO_PERIM_CEFALICO', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('NU_NACIDO_PERIM_TORACICO', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('NU_TEMPERATURA', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{1,2}$')])),
                ('CO_RESULTADO_EF', models.CharField(blank=True, max_length=2, null=True)),
                ('NU_EDAD_EXAMEN_FISICO', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{1,2}$')])),
                ('CO_UM_EDAD', models.CharField(blank=True, max_length=2, null=True)),
                ('DURACION_EMBARAZO_PARTO', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(42)])),
                ('ATIENDE_PARTO', models.CharField(blank=True, max_length=2, null=True)),
                ('CONDICION_PARTO', models.CharField(blank=True, max_length=2, null=True)),
                ('TIPO_PARTO', models.CharField(blank=True, max_length=2, null=True)),
                ('FINANCIADOR_PARTO', models.CharField(blank=True, max_length=2, null=True)),
                ('CO_POSICION_PARTO', models.CharField(blank=True, max_length=2, null=True)),
                ('IN_PARTOGRAMA', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='PARTG')),
                ('IN_ACOMPANA_PARTO', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='APARTO')),
                ('CO_DURACION_PARTO', models.CharField(blank=True, max_length=2, null=True)),
                ('IN_EPISIOTOMIA_PARTO', models.CharField(blank=True, max_length=2, null=True)),
                ('IN_DESGARRO_PARTO', models.CharField(blank=True, max_length=2, null=True)),
                ('CO_ALUMBRAMIENTO_PARTO', models.CharField(blank=True, max_length=2, null=True)),
                ('IN_PLACENTA_PARTO', models.CharField(blank=True, max_length=2, null=True)),
                ('IN_EESS_PROCEDENCIA', models.CharField(blank=True, max_length=2, null=True)),
                ('CO_EESS_PROCENDENCIA', models.CharField(blank=True, max_length=8, null=True)),
                ('CODIGO_LOCAL', models.CharField(blank=True, max_length=8, null=True)),
                ('CODIGO_RENAES', models.CharField(blank=True, max_length=8, null=True)),
                ('CODIGO_OPERACION', models.CharField(blank=True, max_length=2, null=True)),
                ('CREATE_BY', models.CharField(blank=True, max_length=15, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
